apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodeconfigs.bundleext.gke.io
spec:
  group: bundleext.gke.io
  names:
    kind: NodeConfig
    plural: nodeconfigs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        envVars:
          items:
            properties:
              name:
                type: string
              value:
                type: string
            type: object
          type: array
        externalInitFile:
          properties:
            hash:
              type: string
            url:
              type: string
          type: object
        initFile:
          format: byte
          type: string
        kind:
          type: string
        metadata:
          type: object
        osImage:
          properties:
            hash:
              type: string
            url:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
