apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: componentpackagelists.bundle.gke.io
spec:
  group: bundle.gke.io
  names:
    kind: ComponentPackageList
    plural: componentpackagelists
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          items:
            properties:
              apiVersion:
                type: string
              kind:
                type: string
              metadata:
                type: object
              spec:
                properties:
                  canonicalName:
                    type: string
                  objectFiles:
                    items:
                      properties:
                        hash:
                          type: string
                        url:
                          type: string
                      type: object
                    type: array
                  objects:
                    items:
                      type: object
                    type: array
                  rawTextFiles:
                    items:
                      properties:
                        hash:
                          type: string
                        url:
                          type: string
                      type: object
                    type: array
                  version:
                    type: string
                type: object
            type: object
          type: array
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
